--1) what is total revenue generated by male vs female
select gender , sum(purchase_amnt) as revenue
from customer
group by(gender)
--2)which cus used discount but still spend more than avg amnt?
select customer_id , purchase_amnt
from customer
where discount_applied='Yes' and 
purchase_amnt > (select avg(purchase_amnt) from customer)
--3)top 5 products with highest avg review rating
select item_purchased , avg(review_rating) from customer
group by item_purchased
order by avg(review_rating) desc 
limit 5
--4)compare avg puchase amnt between standard and express shipping
select shipping_type , avg(purchase_amnt) from customer
where shipping_type in ('Standard','Express')
group by shipping_type
--5)compare avg spend and total revenue between subscriber and non subscriber
select count(*) as total_cus ,avg(purchase_amnt) , sum(purchase_amnt) , subscription_status from customer
group by subscription_status

--6)which 5 product have highest percentage of purchase after discount appliead?
SELECT 
    item_purchased,
    COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS discount_purchase_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_purchase_percentage DESC
LIMIT 5;

--7)segment cus into new,returning,loyal based on thier totl no. of previous purchase and show count
-- of each segment
with cus_type as (select customer_id , previous_purchases, 
CASE 
WHEN previous_purchases = 1 THEN 'new'
     WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
	 ELSE 'loyal' END AS customer_segment
	 from customer)
select customer_segment, count(*) from cus_type
group by customer_segment
--8)what are top 3 most purchaesd product in each category
WITH ranked_products AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        DENSE_RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS product_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    category,
    item_purchased,
    total_purchases
FROM ranked_products
WHERE product_rank <= 3;
--9)cus who are repeat buyers(more than  5 prev purchase) are tend to be  subscribers?
select subscription_status, count(customer_id) as repeat_buyers from customer
where previous_purchases>5
group by subscription_status
--10)what is revenue contribute of each grp
select sum(purchase_amnt) , age_grp from customer group by age_grp
-- see column names
SELECT * FROM customer LIMIT 0;